# Generated by Django 4.1.5 on 2023-03-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_cae_design_prototype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cae",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="CAE/"),
        ),
        migrations.AlterField(
            model_name="design",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="Design/"),
        ),
        migrations.AlterField(
            model_name="prototype",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="Prototype/"),
        ),
        migrations.AlterField(
            model_name="styling",
            name="file",
            field=models.FileField(default=None, null=True, upload_to="Styling/"),
        ),
    ]
